modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/BenLi06/mtrsurveyor/issues"

[[mods]]
modId="mtrsurveyor"
version="${version}"
displayName="[CRTools]MTR:Xaero Mapper"
description='''Automatically syncs MTR Stations & Depots as waypoints to Xaero's World Map / Minimap. Supports station and platform display modes.'''
logoFile="assets/mtrsurveyor/icon.png"
authors="BenLi06"

[[dependencies.mtrsurveyor]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.mtrsurveyor]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.mtrsurveyor]]
modId="mtr"
mandatory=true
versionRange="[${mtr_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.mtrsurveyor]]
modId="xaerominimap"
mandatory=false
versionRange="*"
ordering="AFTER"
side="CLIENT"

[[dependencies.mtrsurveyor]]
modId="xaeroworldmap"
mandatory=false
versionRange="*"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="mtrsurveyor.mixins.json"
