modLoader = "javafml" #mandatory
loaderVersion = "[46, 48)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "All Rights Reserved" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "xaeroworldmap" #mandatory
version = "1.40.11" #mandatory
displayName = "Xaero's World Map" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "xaeroworldmap.png" #optional
credits = "" #optional
authors = "xaero96" #optional
description = '''A self-writing fullscreen map which also works as an add-on to Xaero's Minimap.''' #mandatory (Supports multiline text)
[[dependencies.xaeroworldmap]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[46, 48)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.xaeroworldmap]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20, 1.20.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.xaeroworldmap]]
modId = "openpartiesandclaims"
mandatory = false
versionRange = "[0.14.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.xaeroworldmap]]
modId = "xaerominimap"
mandatory = false
versionRange = "[25.3.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.xaeroworldmap]]
modId = "xaerobetterpvp"
mandatory = false
versionRange = "[25.3.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.xaeroworldmap]]
modId = "xaerolib"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "NONE"
side = "BOTH"
